name: Cleanup old branches
on:
  push:
    branches:
      - master
      - main
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.6
        with:
          repo_token: ${{ github.token }}
          date: '1 day ago'
          dry_run: true
          delete_tags: false
          minimum_tags: 5
          extra_protected_branch_regex: ^(demo-docs-update|endpoint-work|v.*|[0-9].*|main)$
          extra_protected_tag_regex: '^v.*'
          exclude_open_pr_branches: false
